# Generated by Django 5.1 on 2024-08-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
