# Generated by Django 5.1 on 2024-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variationcategory_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AlterModelOptions(
            name='variationcategory',
            options={'verbose_name': 'Variation Category', 'verbose_name_plural': 'Variation Categories'},
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['id', 'variation_category'], name='products_va_id_7b5280_idx'),
        ),
        migrations.AddIndex(
            model_name='variationcategory',
            index=models.Index(fields=['id', 'name'], name='products_va_id_577655_idx'),
        ),
    ]
