# Generated by Django 5.1 on 2024-08-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
    ]
