# Generated by Django 5.1 on 2024-08-31 02:28

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/images/products/%Y/%m/%d/', validators=[products.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='uploads/images/products/gallery/%Y/%m/%d/', validators=[products.validators.validate_image_size]),
        ),
    ]
