# Generated by Django 5.1 on 2024-08-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
