# Generated by Django 5.1 on 2024-08-31 03:00

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/images/products/%Y/%m/%d/', validators=[products.validators.validate_image_size]),
        ),
    ]
