# Generated by Django 5.1 on 2024-08-31 06:18

import cloudinary.models
import products.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[products.validators.validate_image_size], verbose_name='image'),
        ),
    ]
